### ISSUE TITLE
CMake error 

### ISSUE THREAD

**Issue by ArJavBi** [kirushyk/kms-windows#12]
Hello,
I'm trying to build kurento server for windows on Fedora 25.
After executing **_kms-windows-port.sh all_** I get following error:

  CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindKurentoHelpers.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KurentoHelpers", but CMake did not find one.

  Could not find a package configuration file provided by "KurentoHelpers"
  with any of the following names:

    KurentoHelpersConfig.cmake
    kurentohelpers-config.cmake

  Add the installation prefix of "KurentoHelpers" to CMAKE_PREFIX_PATH or set
  "KurentoHelpers_DIR" to a directory containing one of the above files.  If
  "KurentoHelpers" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/kserver/Downloads/kms-windows-master/contrib/kms-windows-port/work/kms-jsonrpc-build/CMakeFiles/CMakeOutput.log".

Any idea how to fix this?

Thanks in advance.

Regards

**Comment by sledz** [comment]
I assume you have to set the **CMAKEVERSION** environment variable to an appropriate value (see doc/kms-cross-compilation.md).

This is used to generate correct path names like `/usr/i686-w64-mingw32/sys-root/mingw/share/cmake-$CMAKEVERSION/Modules/`

And please do a clean build after this!

**Comment by ArJavBi** [comment]
Thanks for the fast response.
Do you mean:
export CMAKEVERSION=3.9 and then clean and run again?

Thanks!

**Comment by sledz** [comment]
Yes.

But you have to check if "3.9" is the right value. For this look at the mentioned path (see above) at your system.

**Comment by ArJavBi** [comment]
Hi,
thank you very much, no cmake error more, but the cloning of ffmpeg takes too long (about 5h) and is not finished yet.
Is this normal?

![image](https://user-images.githubusercontent.com/31589233/30939427-aaa0eb7c-a3dd-11e7-8233-4b7fe08966a0.png)

**Comment by sledz** [comment]
Sorry. Can't say anything to the fetch behaviour. May be something temporary at the ffmpeg servers?

**Comment by ArJavBi** [comment]
Hi, 
after the third attempt, I got it compiled, but after starting the kurento-media-server.exe I get the following exception:

![image](https://user-images.githubusercontent.com/31589233/31024931-ef845184-a540-11e7-8f6c-0cdb07e2c0bf.png)

Any idea how to fix this?

Thanks.

**Comment by sledz** [comment]
Sorry, can't help on this.
But I would suggest to create a separate issue for this problem and close this one here.
