### ISSUE TITLE
Unable to find gstreamer dll

### ISSUE THREAD

**Issue by chris64digital** [kirushyk/kms-windows#2]
When I start the server I receive:

(kurento-media-server.exe:22832): GStreamer-WARNING **: Failed to load plugin 'C:\Git\kurento\lib\gstreamer-1.0\libgstopus.dll': 'C:\Git\kurento\lib\gstreamer-1.0\libgstopus.dll': The specified module could not be found.

The file is present in the folder specified in the error. I have tried running this with administrator privileges.

**Comment by kirushyk** [comment]
Thank you, yesterday I forgot to add one .dll file into `bin/` subfolder.
https://github.com/kirushyk/kms-windows/releases/tag/v6.4.1-alpha.10
